In [1]:
import nltk

In [6]:
paragraph = """Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."""
               
paragraph

"Thank you all so very much. Thank you to the Academy. \n               Thank you to all of you in this room. I have to congratulate \n               the other incredible nominees this year. The Revenant was \n               the product of the tireless efforts of an unbelievable cast\n               and crew. First off, to my brother in this endeavor, Mr. Tom \n               Hardy. Tom, your talent on screen can only be surpassed by \n               your friendship off screen … thank you for creating a t\n               ranscendent cinematic experience. Thank you to everybody at \n               Fox and New Regency … my entire team. I have to thank \n               everyone from the very onset of my career … To my parents; \n               none of this would be possible without you. And to my \n               friends, I love you dearly; you know who you are. And lastly,\n               I just want to say this: Making The Revenant was about\n               man's relationship to the nat

In [7]:
#first we will tokenize all different sentences and then preprocess (removing all impurities)
import re
#importing regular expression library for preprocessing

In [8]:
dataset = nltk.sent_tokenize(paragraph)
dataset

['Thank you all so very much.',
 'Thank you to the Academy.',
 'Thank you to all of you in this room.',
 'I have to congratulate \n               the other incredible nominees this year.',
 'The Revenant was \n               the product of the tireless efforts of an unbelievable cast\n               and crew.',
 'First off, to my brother in this endeavor, Mr. Tom \n               Hardy.',
 'Tom, your talent on screen can only be surpassed by \n               your friendship off screen … thank you for creating a t\n               ranscendent cinematic experience.',
 'Thank you to everybody at \n               Fox and New Regency … my entire team.',
 'I have to thank \n               everyone from the very onset of my career … To my parents; \n               none of this would be possible without you.',
 'And to my \n               friends, I love you dearly; you know who you are.',
 "And lastly,\n               I just want to say this: Making The Revenant was about\n               man's

In [9]:
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower() #converting everything to lower case
    dataset[i] = re.sub(r'\W',' ',dataset[i]) #this will substitute all the non word characters with space
    dataset[i] = re.sub(r'\s+',' ',dataset[i]) #so this wherever there will be 1 or more space this will subtitute it
                                               #with single space
dataset
#now this data is ready to create the BOW model

['thank you all so very much ',
 'thank you to the academy ',
 'thank you to all of you in this room ',
 'i have to congratulate the other incredible nominees this year ',
 'the revenant was the product of the tireless efforts of an unbelievable cast and crew ',
 'first off to my brother in this endeavor mr tom hardy ',
 'tom your talent on screen can only be surpassed by your friendship off screen thank you for creating a t ranscendent cinematic experience ',
 'thank you to everybody at fox and new regency my entire team ',
 'i have to thank everyone from the very onset of my career to my parents none of this would be possible without you ',
 'and to my friends i love you dearly you know who you are ',
 'and lastly i just want to say this making the revenant was about man s relationship to the natural world ',
 'a world that we collectively felt in 2015 as the hottest year in recorded history ',
 'our production needed to move to the southern tip of this planet just to be able to find

In [10]:
#Creating the histogram
#so first we need a list/dictionary of all the different words mapped with no. of times those words appear
word2count = {} #this is how you declare a dictionary in python

for data in dataset:
    words = nltk.word_tokenize(data) #this will tokenize every sentence into words
    for word in words: #nested loop
        if word not in word2count.keys():
            word2count[word] = 1 #this mean this word have not appeared in any of the previous sentences
        else:
            word2count[word] += 1 #if the word is already in the dictionary we are simply going to increase the count
#so in this way we will get all the different words mapped with no. of times they occured in the whole corpus of doc

word2count

{'thank': 8,
 'you': 12,
 'all': 4,
 'so': 2,
 'very': 3,
 'much': 2,
 'to': 16,
 'the': 17,
 'academy': 1,
 'of': 10,
 'in': 4,
 'this': 9,
 'room': 1,
 'i': 6,
 'have': 3,
 'congratulate': 1,
 'other': 1,
 'incredible': 1,
 'nominees': 1,
 'year': 2,
 'revenant': 2,
 'was': 2,
 'product': 1,
 'tireless': 1,
 'efforts': 1,
 'an': 1,
 'unbelievable': 1,
 'cast': 1,
 'and': 8,
 'crew': 1,
 'first': 1,
 'off': 2,
 'my': 5,
 'brother': 1,
 'endeavor': 1,
 'mr': 1,
 'tom': 2,
 'hardy': 1,
 'your': 2,
 'talent': 1,
 'on': 1,
 'screen': 2,
 'can': 1,
 'only': 1,
 'be': 4,
 'surpassed': 1,
 'by': 3,
 'friendship': 1,
 'for': 10,
 'creating': 1,
 'a': 2,
 't': 1,
 'ranscendent': 1,
 'cinematic': 1,
 'experience': 1,
 'everybody': 1,
 'at': 1,
 'fox': 1,
 'new': 1,
 'regency': 1,
 'entire': 2,
 'team': 1,
 'everyone': 1,
 'from': 1,
 'onset': 1,
 'career': 1,
 'parents': 1,
 'none': 1,
 'would': 2,
 'possible': 1,
 'without': 1,
 'friends': 1,
 'love': 1,
 'dearly': 1,
 'know': 1,
 'who': 4,
 '

In [11]:
#now we will filter the words
import heapq
#importing the heapq library to find n most frequent words out of the whole dictionary

In [12]:
freq_words = heapq.nlargest(100, word2count, key=word2count.get) 
#it will get us 100 most frequent words from dictionary the third parameter will take that based on which key are we 
#going to find the n largest here we will just pass word2count.get
freq_words

['the',
 'to',
 'you',
 'of',
 'for',
 'this',
 'thank',
 'and',
 'i',
 'my',
 'all',
 'in',
 'be',
 'who',
 'world',
 'very',
 'have',
 'by',
 'we',
 'our',
 'is',
 'not',
 'people',
 'out',
 'so',
 'much',
 'year',
 'revenant',
 'was',
 'off',
 'tom',
 'your',
 'screen',
 'a',
 'entire',
 'would',
 'just',
 's',
 'collectively',
 'planet',
 'it',
 'most',
 'need',
 'do',
 'speak',
 'billions',
 'there',
 'children',
 'tonight',
 'take',
 'granted',
 'academy',
 'room',
 'congratulate',
 'other',
 'incredible',
 'nominees',
 'product',
 'tireless',
 'efforts',
 'an',
 'unbelievable',
 'cast',
 'crew',
 'first',
 'brother',
 'endeavor',
 'mr',
 'hardy',
 'talent',
 'on',
 'can',
 'only',
 'surpassed',
 'friendship',
 'creating',
 't',
 'ranscendent',
 'cinematic',
 'experience',
 'everybody',
 'at',
 'fox',
 'new',
 'regency',
 'team',
 'everyone',
 'from',
 'onset',
 'career',
 'parents',
 'none',
 'possible',
 'without',
 'friends',
 'love',
 'dearly',
 'know',
 'are',
 'lastly']

In [15]:
#Now we will build the BOW model

X = [] #this will contain the whole BOW model
#now in each BOW model each document is represented as a vector of 0's and 1's 

for data in dataset:
    vector = [] #this is going to contain the complete vector for each of the documents
    for word in freq_words: #to check which of the frequent words are in the document
        if word in nltk.word_tokenize(data): #if word is in tokenized document
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)

#X is list of lists
print(X)
#here X contains 21 elements i.e., 21 documents and each of those elements is a list and the size of the list is 100.

[[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [17]:
#Now we are going to create a 2d array from this to easily visualize and we can do it with numpy
import numpy as np

In [18]:
#we will store the 2d array in the same variable i.e., X
X = np.asarray(X)
X

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [19]:
print(X)

[[0 0 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
